---
dependencies:

galaxy_info:
  author: "Chris Olstrom"
  company: "TELUS digital"
  description: "fish - the friendly interactive shell"
  license: MIT
  platforms:
    - name: Ubuntu
      versions:
      - precise
      - trusty
      - utopic
  categories:
    - system
